### ISSUE TITLE
Can't compile with Flutter 3.29

### ISSUE THREAD

**Issue by ccoelho-dzk** [pendo-io/pendo-mobile-sdk#226]
**Android 15**

**3.2.0**

**Framework**
 Flutter

**Describe the bug**
Not able to compile applications using the latest pendo_sdk Flutter package (3.5.3) and the latest stable Flutter version (3.29).

**To Reproduce**
1. Build an app using Pendo's pendo_sdk Flutter package and Flutter's latest stable release.

**Expected behavior**
To compile and run the application using the latest Flutter stable release.

**Logs**
```
/Users/user-name/.pub-cache/hosted/pub.dev/pendo_sdk-3.5.3/android/src/main/java/pendo/io/pendo_sdk/PendoFlutterPlugin.java:20: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
/Users/user-name/.pub-cache/hosted/pub.dev/pendo_sdk-3.5.3/android/src/main/java/pendo/io/pendo_sdk/FlutterPluginBridge.java:16: error: cannot find symbol
import io.flutter.view.FlutterView;
                      ^
  symbol:   class FlutterView
  location: package io.flutter.view
/Users/user-name/.pub-cache/hosted/pub.dev/pendo_sdk-3.5.3/android/src/main/java/pendo/io/pendo_sdk/FlutterPluginBridge.java:101: error: cannot find symbol
            if (mRenderer.getClass() == FlutterView.class) {
                                        ^
  symbol:   class FlutterView
  location: class FlutterPluginBridge
/Users/user-name/.pub-cache/hosted/pub.dev/pendo_sdk-3.5.3/android/src/main/java/pendo/io/pendo_sdk/FlutterPluginBridge.java:102: error: cannot find symbol
                bitmap = ((FlutterView) mRenderer).getBitmap();
                           ^
  symbol:   class FlutterView
  location: class FlutterPluginBridge
Note: /Users/user-name/.pub-cache/hosted/pub.dev/pendo_sdk-3.5.3/android/src/main/java/pendo/io/pendo_sdk/PendoFlutterPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pendo_sdk:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 17s
```

**Comment by noambartouv** [comment]
This is an issue starting from Flutter 3.29.0. We are looking into it and will update once a fix is available.

**Comment by rzubascu** [comment]
@noambartouv is there an ETA on this? Thanks!

**Comment by DavidPendo** [comment]
There is a known issue with Flutter SDK 3.29.0 that causes Android compilation failures. This will be resolved in the upcoming 3.6.1 Pendo plugin hotfix, which is planned to be released within the next two weeks.

**Comment by randmaayan** [comment]
Hi @ccoelho-dzk @rzubascu 
We've just released a fix for this issue. 
Please take 3.6.1 of our plugin https://pub.dev/packages/pendo_sdk
